name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Verify build output
        run: |
          echo "Listing dist/public"
          ls -la ./dist/public || true
          echo "Show index.html head"
          if [ -f ./dist/public/index.html ]; then head -n 10 ./dist/public/index.html; else echo "index.html not found"; fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4